# Generated by Django 3.0.3 on 2020-08-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='membership_status',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Name', models.TextField(max_length=100)),
                ('Receipt_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Father_Name', models.TextField(max_length=100)),
                ('Mother_Nme', models.TextField(max_length=100)),
                ('Dob', models.DateField()),
                ('Age', models.IntegerField()),
                ('Education', models.TextField(max_length=100)),
                ('Address', models.TextField(max_length=100)),
                ('City', models.TextField(max_length=100)),
                ('State', models.TextField(max_length=100)),
                ('Family_members_count', models.IntegerField()),
                ('Occupation', models.TextField(max_length=100)),
                ('Monthly_income', models.IntegerField()),
                ('Volunteer_id', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ngo_staff',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Name', models.TextField(max_length=100)),
                ('Enrollment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateOfEnrollment', models.DateField(auto_now_add=True)),
                ('Father_Name', models.TextField(max_length=100)),
                ('Mother_Nme', models.TextField(max_length=100)),
                ('Dob', models.DateField()),
                ('Age', models.IntegerField()),
                ('Education', models.TextField(max_length=100)),
                ('Address', models.TextField(max_length=100)),
                ('City', models.TextField(max_length=100)),
                ('State', models.TextField(max_length=100)),
                ('Login_password', models.TextField(max_length=100)),
                ('User_role', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
