# Generated by Django 3.0.3 on 2020-08-16 08:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('Description', models.TextField(max_length=1000)),
                ('Income_lowerbound', models.IntegerField()),
                ('Income_upperbound', models.IntegerField()),
                ('Gender', models.TextField(max_length=10)),
                ('Adhar', models.BooleanField(default=True)),
                ('PanCard', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('AGE', models.IntegerField()),
                ('Education_qualification', models.CharField(choices=[('below_10th', 'below_10th'), ('10th', '10th'), ('12th', '12th'), ('Graduation', 'Graduation'), ('Post_Grad', 'Post_Grad')], max_length=10)),
                ('Address', models.TextField(max_length=100)),
                ('Number_of_family_members', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('montly_income', models.IntegerField()),
                ('gender_choice', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('Document_collected', models.BooleanField(null=True)),
                ('membership', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('AGE', models.IntegerField()),
                ('Education_qualification', models.CharField(choices=[('below_10th', 'below_10th'), ('10th', '10th'), ('12th', '12th'), ('Graduation', 'Graduation'), ('Post_Grad', 'Post_Grad')], max_length=10)),
                ('Address', models.TextField(max_length=100)),
                ('Number_of_family_members', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('gender_choice', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
