create table users (
  id integer primary key autoincrement,
  name varchar(100) ,
  date_ varchar(100) ,
  father varchar(100) ,
  mother varchar(100) ,
  dob varchar(100) ,
  age int ,
  gender varchar(100) ,
  phone varchar(100) ,
  email varchar(100),
  education varchar(100) ,
  address varchar(100) ,
  fam int ,
  occupation varchar ,
  monthly int ,
  volunteer_id varchar ,
  docs int ,
  membership int
);
